### ISSUE TITLE
qmacro Thinking Aloud Python code ^_^

### ISSUE THREAD

**Issue by yasinnaal** [qmacro/thinking-aloud#14]
#qmacro Thinking Aloud

categories  = ["Major", "Minor", "Mini", "Micro"]
blog = ["qmacro.org SAP Community", "autodidactics", "(something missing)", "Twitter"]
blog_e_length = len(blog)
blog_c_length = sum(len(i) for i in blog)
hdash = "-"* (blog_e_length + blog_c_length)
def DrawBoard(rows,cols):   
    print(hdash)
    for r1 in range(0,cols):       
            line1length = len(blog[r1]) -  len (categories[r1])            
            print(categories[r1] + " " * line1length  + "|", end = '')
    print()  
    for r2 in range(0,cols):       
            print(blog[r2] + ""  + "|", end = '')
    print()   
    print(hdash)
DrawBoard(2, len(categories))
![qmacroThinkingAloud](https://user-images.githubusercontent.com/42123587/113161041-ae9fb400-9246-11eb-9d28-366fb841aabf.PNG)

**Comment by yasinnaal** [comment]
Hi 

i was reading your Thinking Aloud blog so i thought to write python code
print your categorization, blog path. once am free i will try the same 
using ABAP too :)

Regards

**Comment by qmacro** [comment]
Hi @yasinnaal thanks for contributing! Have you written an ABAP version yet? Perhaps post it in the SAP Community to share. 

By the way, I have a question for you - if your issue had been auto-deleted (as the issues are for primarily for me to write and my thoughts) - how would you have felt? Would you have been OK with that? Just curious; @rsletta and I are discussing this over on #18.

**Comment by yasinnaal** [comment]
Hi DJ Adams @qmacro  
Thanks for your reply. Please feel free to delete the issue it is absolutely OK.
i have created a small ABAP pro attached bellow as  text file,  you can find github link for the same too
if it is OK with you yes i can post on SAP Community but under what section?
 
[ZABAP_THINKINGALOUD.txt](https://github.com/qmacro/thinking-aloud/files/6276980/ZABAP_THINKINGALOUD.txt)

[https://github.com/yasinnaal/ABAP-YN/blob/c6d32332dd6e1c122501895437a70f674c359aea/THINKINGALOUD/ZABAP_THINKINGALOUD](url)

Thanks

**Comment by qmacro** [comment]
Hi @yasinnaal I think the [SAP Community Coffee Corner](https://answers.sap.com/content/kbentry/list.html) might be a great place for it. Closing this issue now. Cheers! DJ

**Comment by yasinnaal** [comment]
Hi @qmacro

https://answers.sap.com/articles/13341880/my-abap-code-thinking-aloud-dj-adams.html

^__^"
